/*
 Warning: Uses mongo-js! (currently no ES6 features)
 Variables to set outside:
 - REGION: The region for the markers
 - NUMBER: How many markers to generate (default: 1)
 */

function getRandomArbitrary(min, max) {
    return Math.random() * (max - min) + min;
}

function generateRegionCoordinates (region) {
    var lat;
    var lng;
    if (region === 'budapest') {
        lat = getRandomArbitrary(47.46013579001151, 47.53644831975808);
        lng = getRandomArbitrary(18.899394755554226, 19.174052958679226);
    } else {
        if (region === 'paks') {
            lat = getRandomArbitrary(46.52616060194396, 46.6813671123628);
            lng = getRandomArbitrary(18.582765345764187, 19.132081752014187);
        } else {
            lat = getRandomArbitrary(44.84723460305939, 49.7450105578486);
            lng = getRandomArbitrary(10.49425292510989, 28.07237792510989);
        }
    }

    return {
        lat: lat, lng: lng
    };
}

function generateMarker (region) {
    var key = region + '-' + Date.now().toString() + '-' + Math.random().toString();
    return {
        _id: key,
        key: key,
        defaultAnimation: 2,
        label: 'Autogenerated',
        position: generateRegionCoordinates(region),
        region: region
    }
}

try {
    var conn = new Mongo();
    var db = conn.getDB('icontest');

    print('*** Start ***');
    print(REGION);
    print(NUMBER);

    var number = 1;
    if (NUMBER) {
        number = NUMBER;
    }

    print(number);

    print('*** Generated marker(s) ***');
    for (var i = 0; i < number ; i++) {
        var marker = generateMarker(REGION);
        db.markers.save(marker);

        print(marker._id);
    }

    print('*** End ***');

}  catch (e) {
    print('Unexpected error!');
    print(e.message);
}
